version: "3"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8000:8000"
    restart: always
    container_name: social_app
    env_file:
      - .env
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

